name = "asm2464pdx"
version = "0.5.0"
[dependencies]
JITX3 = { path = "{SLM_ROOT}/JITX3" }
jsl = { git = "johnsel/jsl", version = "0.10.4" }
jlc-pcb = { git = "Johnsel/jlc-pcb", version = "0.4.3" }
connectors = { git = "JITx-Inc/connectors", version = "0.4.1" }
diodes = { git = "JITx-Inc/diodes", version = "0.2.0" }
FTDI = { git = "JITx-Inc/FTDI", version = "0.3.3" }
TI-vreg = { git = "JITx-Inc/TI-VREG", version = "0.3.4" }
power-systems = { git = "JITx-Inc/power-systems", version = "0.5.0" }
debug = { git = "JITx-Inc/debug", version = "0.3.3" }
